### ISSUE TITLE
Temperature 0.0

### ISSUE THREAD

**Issue by mksmo** [clauzewitz/homebridge-raspberrypi-remote#1]
Hello!
With standard config there is no temperature.
![rpihb](https://user-images.githubusercontent.com/4104873/60434835-bfa23800-9c10-11e9-8690-bc1bc100d2bd.JPG)

![unnamed](https://user-images.githubusercontent.com/4104873/60434940-fd06c580-9c10-11e9-993e-5615f27128d0.jpg)

And Reboot button doesn't perform "reboot now" on raspberry:
```
0|homebridge  | [7/1/2019, 3:49:34 PM] [Raspberry Pi] { Error: Command failed: reboot
0|homebridge  | Failed to set wall message, ignoring: Interactive authentication required.
0|homebridge  | Failed to reboot system via logind: Interactive authentication required.
0|homebridge  | Failed to open /dev/initctl: Permission denied
0|homebridge  | Failed to talk to init daemon.
0|homebridge  |     at ChildProcess.exithandler (child_process.js:294:12)
0|homebridge  |     at ChildProcess.emit (events.js:189:13)
0|homebridge  |     at maybeClose (internal/child_process.js:970:16)
0|homebridge  |     at Socket.stream.socket.on (internal/child_process.js:389:11)
0|homebridge  |     at Socket.emit (events.js:189:13)
0|homebridge  |     at Pipe._handle.close (net.js:597:12) killed: false, code: 1, signal: null, cmd: 'reboot' }

```

**Comment by clauzewitz** [comment]
Thank you for telling me about the bug. We will fix the bug where the temperature of 'Raspberry Pie' is not displayed.
In addition, the problem that 'Raspberry Pie' is not restarted is being corrected now.

**Comment by paskovitch** [comment]
add chmod 777 to /usr/lib/node_modules/homebridge-raspberrypi-remote/current_temperature.sh
