### ISSUE TITLE
Reboot fails due to permissions

### ISSUE THREAD

**Issue by mbierman** [clauzewitz/homebridge-raspberrypi-remote#6]
When I try to reboot I see: 

```
[4/17/2020, 3:29:20 AM] [Raspberry Pi] Error: Command failed: reboot
Failed to set wall message, ignoring: Interactive authentication required.
Failed to reboot system via logind: Interactive authentication required.
Failed to open initctl fifo: Permission denied
Failed to talk to init daemon.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'reboot'
}
```

I think the following line in index.js is the problem. 
`	exec('shutdown -h now', function (error, stdout, stderr) {`

This seems to work when i use the commandline:
`	exec('sudo shutdown -r now', function (error, stdout, stderr) {`

**Comment by monza258** [comment]
You can change the index.js file

`sudo nano /usr/local/lib/node_modules/homebridge-raspberrypi-remote/index.js`

see:
exec('reboot', function (error, stdout, stderr)

Chance to:
exec('sudo reboot', function (error, stdout, stderr)

Done

**Comment by mbierman** [comment]
Thanks. I can't verify this anymore because I switched to running homebridge on my Synology so I will just close this. But this was helpful nonetheless.
